### PR TITLE
Fixed typos in _urlSpaceRegex, _getSameOriginLinkHref and _makeRegExp

### PR DESCRIPTION
**Pull request by zboralski**
This should settle issue #7

### CODE REVIEW

**Comment by zboralski** [comment]
I signed it!

**Comment by zboralski** [comment]
Signed as company Belua Systems Limited

**Comment by rictic** [comment]
This looks good, thanks for the contribution!

I'm looking in the CLA signers database and I can't find you. Can you verify that you signed with the same email address that you use for your git commits?

**Comment by zboralski** [comment]
@rictic yes... I signed and it says : "It looks like you've already signed this CLA."

and it is the same email address as I used in the git commit. the google company group is dev@ (same domain)

**Comment by zboralski** [comment]
Just ran git config --global user.email and it is set correctly
`z@belua.com`

**Comment by zboralski** [comment]
@rictic I added a small commit that I didn't push to github. All checks have passed and it show I cla:yes

**Comment by rictic** [comment]
Thanks for the PR, and sorry about the CLA weirdness!

**Pull request merged**
